import React, { useState } from 'react';

const CodeBlock: React.FC<{ code: string }> = ({ code }) => {
    const [copied, setCopied] = useState(false);
    const copyToClipboard = () => {
        navigator.clipboard.writeText(code.trim());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="bg-gray-900 text-white p-4 rounded-md text-xs relative my-2">
            <pre><code>{code.trim()}</code></pre>
            <button 
                onClick={copyToClipboard} 
                className="absolute top-2 right-2 bg-gray-700 hover:bg-gray-600 text-white px-2 py-1 rounded text-xs transition-colors"
            >
                {copied ? 'Copied!' : 'Copy'}
            </button>
        </div>
    );
};

interface SupabaseSetupGuideProps {
    onClose: () => void;
}

const SupabaseSetupGuide: React.FC<SupabaseSetupGuideProps> = ({ onClose }) => {
    const [activeTab, setActiveTab] = useState<'auth' | 'helpers' | 'core_rls' | 'general_rls' | 'advanced_rls' | 'audit'>('auth');
    
    const authFunctionCode = `
-- 1. Add tenant_id to profiles table (run this once)
-- This ensures each user profile is linked to a tenant for security policies.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tenant_id uuid;

-- 2. Update the function to include tenant_id on new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, group_id, tenant_id)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url',
    -- Use group_id from metadata if present (from invitation), otherwise default
    COALESCE(NEW.raw_user_meta_data->>'group_id', 'group-data-entry'),
    (NEW.raw_user_meta_data->>'tenant_id')::uuid
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
    `;

    const authTriggerCode = `
-- After creating the function above, create the trigger to run it.
-- This automatically creates a public profile when a new user signs up in Supabase Auth.

-- First, drop the old trigger if it exists to avoid errors
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Then, create the new trigger
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();
    `;
    
    const auditTableCode = `
-- Create the table to store audit logs
CREATE TABLE public.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id),
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text,
  old_record_json jsonb,
  new_record_json jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);
    `;

    const auditFunctionCode = `
-- Create a function to be called by triggers
CREATE OR REPLACE FUNCTION public.log_farmer_changes()
RETURNS TRIGGER AS $$
DECLARE
  user_id_from_auth uuid := auth.uid();
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.audit_log (user_id, action, table_name, record_id, new_record_json)
    VALUES (user_id_from_auth, 'INSERT', TG_TABLE_NAME, NEW.id, row_to_json(NEW));
    RETURN NEW;
  ELSIF (TG_OP = 'UPDATE') THEN
    INSERT INTO public.audit_log (user_id, action, table_name, record_id, old_record_json, new_record_json)
    VALUES (user_id_from_auth, 'UPDATE', TG_TABLE_NAME, NEW.id, row_to_json(OLD), row_to_json(NEW));
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    -- Note: We log the OLD record on delete
    INSERT INTO public.audit_log (user_id, action, table_name, record_id, old_record_json)
    VALUES (user_id_from_auth, 'DELETE', TG_TABLE_NAME, OLD.id, row_to_json(OLD));
    RETURN OLD;
  END IF;
  RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
    `;

    const auditTriggerCode = `
-- Drop existing triggers to be safe
DROP TRIGGER IF EXISTS farmers_audit_insert ON public.farmers;
DROP TRIGGER IF EXISTS farmers_audit_update ON public.farmers;
DROP TRIGGER IF EXISTS farmers_audit_delete ON public.farmers;

-- Create triggers to call the function on any data change
CREATE TRIGGER farmers_audit_insert
AFTER INSERT ON public.farmers
FOR EACH ROW EXECUTE FUNCTION public.log_farmer_changes();

CREATE TRIGGER farmers_audit_update
AFTER UPDATE ON public.farmers
FOR EACH ROW EXECUTE FUNCTION public.log_farmer_changes();

CREATE TRIGGER farmers_audit_delete
AFTER DELETE ON public.farmers
FOR EACH ROW EXECUTE FUNCTION public.log_farmer_changes();
    `;

    const auditViewCode = `
-- Create a view for easier querying, joining with profiles to get user names
CREATE OR REPLACE VIEW public.audit_log_view AS
SELECT
  al.id,
  al.user_id,
  p.full_name AS user_name,
  al.action,
  al.table_name,
  al.record_id,
  al.old_record_json,
  al.new_record_json,
  al.created_at
FROM public.audit_log al
LEFT JOIN public.profiles p ON al.user_id = p.id;
    `;

    const rlsHelperFunctions = `
-- Helper function to get the current user's tenant_id from their profile
-- This is the foundation for all our security policies.
CREATE OR REPLACE FUNCTION public.get_current_tenant_id()
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_tenant_id uuid;
BEGIN
  SELECT tenant_id INTO user_tenant_id
  FROM public.profiles
  WHERE id = auth.uid();
  RETURN user_tenant_id;
END;
$$;


-- Helper function to get the current user's permissions from their group
CREATE OR REPLACE FUNCTION public.get_user_permissions()
RETURNS text[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_group_id text;
  user_permissions text[];
BEGIN
  -- Get the user's group_id from their profile
  SELECT group_id INTO user_group_id
  FROM public.profiles
  WHERE id = auth.uid();

  -- Get the permissions for that group
  SELECT permissions INTO user_permissions
  FROM public.groups
  WHERE id = user_group_id;

  RETURN user_permissions;
END;
$$;
    `;

    const coreRlsPolicies = `
--- PROFILES TABLE ---
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow tenant-scoped read access" ON public.profiles;
DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;

-- Users can see other users within their own tenant
CREATE POLICY "Allow tenant-scoped read access"
ON public.profiles FOR SELECT
USING (tenant_id = public.get_current_tenant_id());

-- Users can update their own profile
CREATE POLICY "Allow users to update their own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);


--- FARMERS TABLE ---
ALTER TABLE public.farmers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farmers FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow tenant-scoped read access" ON public.farmers;
DROP POLICY IF EXISTS "Allow insert for authorized users" ON public.farmers;
DROP POLICY IF EXISTS "Allow update for authorized users" ON public.farmers;
DROP POLICY IF EXISTS "Allow delete for authorized users" ON public.farmers;

CREATE POLICY "Allow tenant-scoped read access" ON public.farmers FOR SELECT
USING (tenant_id = public.get_current_tenant_id());

CREATE POLICY "Allow insert for authorized users" ON public.farmers FOR INSERT
WITH CHECK (tenant_id = public.get_current_tenant_id() AND 'CAN_REGISTER_FARMER' = ANY(public.get_user_permissions()));

CREATE POLICY "Allow update for authorized users" ON public.farmers FOR UPDATE
USING (tenant_id = public.get_current_tenant_id() AND 'CAN_EDIT_FARMER' = ANY(public.get_user_permissions()));

CREATE POLICY "Allow delete for authorized users" ON public.farmers FOR DELETE
USING (tenant_id = public.get_current_tenant_id() AND 'CAN_DELETE_FARMER' = ANY(public.get_user_permissions()));


--- SUBSIDY PAYMENTS TABLE ---
ALTER TABLE public.subsidy_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subsidy_payments FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow tenant-scoped read access" ON public.subsidy_payments;
DROP POLICY IF EXISTS "Allow insert for authorized users" ON public.subsidy_payments;
DROP POLICY IF EXISTS "Allow update for authorized users" ON public.subsidy_payments;

CREATE POLICY "Allow tenant-scoped read access" ON public.subsidy_payments FOR SELECT
USING (tenant_id = public.get_current_tenant_id());

CREATE POLICY "Allow insert for authorized users" ON public.subsidy_payments FOR INSERT
WITH CHECK (tenant_id = public.get_current_tenant_id() AND 'CAN_EDIT_FARMER' = ANY(public.get_user_permissions()));

-- Allow updates as well for editing functionality
CREATE POLICY "Allow update for authorized users" ON public.subsidy_payments FOR UPDATE
USING (tenant_id = public.get_current_tenant_id() AND 'CAN_EDIT_FARMER' = ANY(public.get_user_permissions()));
    `;

    const generalTenantPolicies = `
-- This script applies a standard tenant isolation policy to multiple tables.
-- It ensures that users can only view or modify data that belongs to their own tenant.
DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'activity_logs', 'agronomic_alerts', 'assistance_applications', 
        'equipment', 'equipment_maintenance_logs', 'events', 'farm_plots', 
        'groups', 'harvests', 'planting_records', 'product_categories', 'products', 
        'quality_assessments', 'resources', 'resource_distributions', 
        'service_points', 'tasks', 'territories', 'vendors', 'visit_requests'
    ]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', table_name);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Tenant Isolation Policy" ON public.%I;', table_name);
        EXECUTE format('
            CREATE POLICY "Tenant Isolation Policy" ON public.%I
            FOR ALL
            USING (tenant_id = public.get_current_tenant_id())
            WITH CHECK (tenant_id = public.get_current_tenant_id());
        ', table_name);
    END LOOP;
END $$;
    `;
    
    const advancedRlsPolicies = `
--- FARMER DEALER CONSENTS ---
-- This policy allows access if the user's tenant is the one granting consent (the farmer's tenant)
-- or the one receiving consent (the dealer's tenant).
ALTER TABLE public.farmer_dealer_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farmer_dealer_consents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow involved tenants to access consents" ON public.farmer_dealer_consents;

CREATE POLICY "Allow involved tenants to access consents" ON public.farmer_dealer_consents
FOR ALL
USING (
    tenant_id = public.get_current_tenant_id() OR
    EXISTS (
        SELECT 1 FROM public.farmers f 
        WHERE f.id = farmer_dealer_consents.farmer_id 
        AND f.tenant_id = public.get_current_tenant_id()
    )
);

--- TERRITORY TRANSFER REQUESTS ---
ALTER TABLE public.territory_transfer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.territory_transfer_requests FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow involved tenants to access transfer requests" ON public.territory_transfer_requests;

CREATE POLICY "Allow involved tenants to access transfer requests" ON public.territory_transfer_requests
FOR ALL
USING (
    from_tenant_id = public.get_current_tenant_id() OR 
    to_tenant_id = public.get_current_tenant_id()
);


--- TERRITORY DISPUTES ---
ALTER TABLE public.territory_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.territory_disputes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow involved tenants to access disputes" ON public.territory_disputes;

CREATE POLICY "Allow involved tenants to access disputes" ON public.territory_disputes
FOR ALL
USING (
    requesting_tenant_id = public.get_current_tenant_id() OR 
    contested_tenant_id = public.get_current_tenant_id()
);
    `;


    return (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex items-center justify-center p-4 z-[100]" onClick={onClose}>
            <div className="bg-gray-800 text-gray-300 rounded-lg shadow-2xl w-full max-w-4xl h-[90vh] flex flex-col" onClick={e => e.stopPropagation()}>
                <div className="p-4 border-b border-gray-700 flex justify-between items-center flex-shrink-0">
                    <h2 className="text-xl font-bold text-white">Supabase Setup Guide</h2>
                    <button onClick={onClose} className="p-2 rounded-full hover:bg-gray-600 transition">
                         <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="flex-1 flex overflow-hidden">
                    <div className="w-1/4 border-r border-gray-700 p-4 space-y-2 overflow-y-auto">
                        <button onClick={() => setActiveTab('auth')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'auth' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>1. Auth & Profiles</button>
                        <button onClick={() => setActiveTab('helpers')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'helpers' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>2. RLS Helper Functions</button>
                        <button onClick={() => setActiveTab('core_rls')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'core_rls' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>3. Core RLS Policies</button>
                        <button onClick={() => setActiveTab('general_rls')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'general_rls' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>4. General Tenant Policies</button>
                        <button onClick={() => setActiveTab('advanced_rls')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'advanced_rls' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>5. Advanced RLS Policies</button>
                        <button onClick={() => setActiveTab('audit')} className={`w-full text-left p-3 rounded-md font-semibold text-sm transition-colors ${activeTab === 'audit' ? 'bg-green-600/20 text-green-300' : 'hover:bg-gray-700'}`}>6. Audit Trail</button>
                    </div>

                    <div className="w-3/4 p-6 overflow-y-auto">
                        {activeTab === 'auth' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">Auth & User Profiles Setup</h3>
                                <p>This ensures new users are correctly linked to their organization (tenant). Run these two scripts in order in the Supabase <strong className="text-gray-200">SQL Editor</strong>.</p>
                                <p className="font-semibold">Step 1: Update profiles table and create user creation function.</p>
                                <CodeBlock code={authFunctionCode} />
                                <p className="font-semibold">Step 2: Create the trigger.</p>
                                <CodeBlock code={authTriggerCode} />
                            </div>
                        )}
                         {activeTab === 'helpers' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">RLS Helper Functions</h3>
                                <p>These SQL functions are required for the security policies to work. They securely identify the current user's organization and permissions.</p>
                                <CodeBlock code={rlsHelperFunctions} />
                            </div>
                        )}
                        {activeTab === 'core_rls' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">Core Security Policies (RLS)</h3>
                                <p className="text-red-400 font-bold">This is a critical security step.</p>
                                <p>These policies control who can access and modify data on the most important tables. This script fixes major security holes from the previous version.</p>
                                <CodeBlock code={coreRlsPolicies} />
                            </div>
                        )}
                         {activeTab === 'general_rls' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">General Tenant Isolation Policies</h3>
                                <p>This script applies a standard, secure RLS policy to over 20 tables that have a `tenant_id` column. It ensures users can only access data from their own organization.</p>
                                <CodeBlock code={generalTenantPolicies} />
                            </div>
                        )}
                         {activeTab === 'advanced_rls' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">Advanced RLS Policies</h3>
                                <p>These policies handle more complex cases where multiple tenants might need access to a single record, such as territory transfers or disputes.</p>
                                <CodeBlock code={advancedRlsPolicies} />
                            </div>
                        )}
                        {activeTab === 'audit' && (
                            <div className="space-y-4">
                                <h3 className="text-lg font-bold text-white">Audit Trail for Analytics</h3>
                                <p>This system logs all changes to the `farmers` table, enabling the Usage Analytics page. Run these scripts in order.</p>
                                <p className="font-semibold">Step 1: Create the audit log table.</p>
                                <CodeBlock code={auditTableCode} />
                                <p className="font-semibold">Step 2: Create the function to log changes.</p>
                                <CodeBlock code={auditFunctionCode} />
                                 <p className="font-semibold">Step 3: Create triggers on the `farmers` table.</p>
                                <CodeBlock code={auditTriggerCode} />
                                <p className="font-semibold">Step 4: Create the view for the application to read.</p>
                                <CodeBlock code={auditViewCode} />
                            </div>
                        )}
                    </div>
                </div>

                <div className="bg-gray-900 p-4 flex justify-end gap-4 rounded-b-lg flex-shrink-0">
                    <button type="button" onClick={onClose} className="px-6 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-500 transition">Close</button>
                </div>
            </div>
        </div>
    );
};

export default SupabaseSetupGuide;